cleaning
new patch

translate test for remote tes

trying to pin some version

update TF

fixupprepare

foo

fixing up that blueprint

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,7 +17,6 @@ orbs:
   node: cloudify/public-unittest-orb@volatile
   wagonorb: cloudify/wagon-bulder-orb@volatile
   releaseorb: cloudify/release-orb@volatile
-  managerorb: cloudify/manager-orb@volatile
   slack: cloudify/notify-slack@2
 
 checkout:
@@ -31,35 +30,49 @@ checkout:
 
 executors:
 
-  py36:
-    environment:
-      PYENV_VERSION: 3.6.5
-    docker:
-      - image: circleci/python:3.6
-
   cloudify-machine-py3:
     machine:
       image: ubuntu-2004:202201-02
 
 commands:
 
+  setup_manager:
+    steps:
+      - run: |
+          if [[ -z "${CLOUDIFY_HOST}" ]]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TENANT}" ]] && [ -z "${CIRCLE_PROJECT_REPONAME}" ]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TOKEN}" ]]; then
+              exit 1
+          fi
+      - run: |
+          response=$(curl --write-out '%{http_code}' --silent --insecure --header "Tenant: ${CLOUDIFY_TENANT}" --header "Authentication-Token: ${CLOUDIFY_TOKEN}" https://$CLOUDIFY_HOST/api/v3.1/status --output /dev/null)
+          if [[ $response != 200 ]]; then
+              echo "Failed to get manager status";
+              exit 1
+          fi
+      - run: pip3 install urllib3==1.26.15 requests-toolbelt==0.10.1
+      - run: pip3 install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/refs/heads/master.zip
+      - run: git submodule update --init --recursive --remote
+
   prepare_test_manager:
     steps:
-      - attach_workspace:
-          at: workspace
-      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE --generate-new-aws-token -es aws_access_key_id=$aws_access_key_id -es aws_secret_access_key=$aws_secret_access_key --yum-package python-netaddr --yum-package git -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*)  ~/project/plugin.yaml
-      - run: ecosystem-test upload-plugin -PN utilities
+      - run: ecosystem-test prepare-remote-test-manager --generate-new-aws-token -es gcp_credentials=$gcp_credentials -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*) ~/project/plugin_1_4.yaml
 
   run_tf_vm_test:
     steps:
-      - run: ecosystem-test local-blueprint-test -b examples/blueprint-examples/virtual-machine/aws-terraform.yaml --test-id=virtual-machine -i aws_region_name=us-west-2 -i env_name="$CIRCLE_BUILD_NUM" --on-failure=uninstall-force --timeout=1800 --nested-test=.circleci/test_features.py
+      - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/virtual-machine/aws-terraform.yaml --test-id=virtual-machine -i aws_region_name=us-west-2 -i env_name="$CIRCLE_BUILD_NUM" --on-failure=uninstall-force --timeout=1800 --nested-test=.circleci/test_features.py
 
   run_ui_test:
     steps:
       - run: wget https://github.com/cloudify-cosmo/cloudify-stage/raw/master/test/cypress/fixtures/blueprints/topology.zip
       - run: unzip topology.zip
-      - run: ecosystem-test local-blueprint-test -b terraform-bp/blueprint.yaml --on-failure=uninstall-force --timeout=1800 --nested-test=.circleci/test_ui_features.py
-
+      - run: ecosystem-test remote-blueprint-test -b terraform-bp/blueprint.yaml --on-failure=uninstall-force --timeout=1800 --nested-test=.circleci/test_ui_features.py
 
 jobs:
   integration_tests_py3:
@@ -68,7 +81,9 @@ jobs:
       CLOUDIFY_SSL_TRUST_ALL: true
     steps:
       - checkout
-      - managerorb/create_manager_container_latest
+      - attach_workspace:
+          at: workspace
+      - setup_manager
       - prepare_test_manager
       - run_tf_vm_test
       - run_ui_test
